# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.CharField(max_length=240, primary_key=True, serialize=False)),
                ('attributes', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementChild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childElementi', to='ProjekatTim6.Element')),
                ('elementParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentElementi', to='ProjekatTim6.Element')),
            ],
        ),
    ]
